function menu_eleccion(obj, init)
  clear h

  h = guidata(obj);

  %% Grupo e Integrantes
  h.grupo = uicontrol('style', 'text',...
		      'string', 'Grupo 6',...
		      'units','normalized',...
		      'position',[0.55 0.75 0.4 0.045]);
  h.integrantes = uicontrol('style', 'text',...
		      'string', 'Integrantes:',...
		      'units','normalized',...
		      'position',[0.55 0.7 0.4 0.045]);
  h.int1 = uicontrol('style', 'text',...
		      'string', '- Gonzales Morales Beckham Luis',...
		      'units','normalized',...
		      'position',[0.55 0.65 0.4 0.045]);
  h.int2 = uicontrol('style', 'text',...
		      'string', '- Moran Aragon Lucia Camila',...
		      'units','normalized',...
		      'position',[0.55 0.6 0.4 0.045]);
  h.int3 = uicontrol('style', 'text',...
		      'string', '- Pozo Velarde Luis Felipe',
		      'units','normalized',...
		      'position',[0.55 0.55 0.4 0.045]);
  h.int4 = uicontrol('style', 'text',...
		      'string', '- Ramirez Chero Alejandro David',...
		      'units','normalized',...
		      'position',[0.55 0.5 0.4 0.045]);
  h.int5 = uicontrol('style', 'text',...
		      'string', '- Saico Merma Cristhian Daniel',...
		      'units','normalized',...
		      'position',[0.55 0.45 0.4 0.045]);
  h.int6 = uicontrol('style', 'text',...
		      'string', '- Vega Astocondor Diego Alonso',...
		      'units','normalized',...
		      'position',[0.55 0.4 0.4 0.045]);


  %% Botones
  h.titulo = uicontrol ('style', 'text',...
			'units', 'normalized',...
			'string', 'Elija una opcion',...
			'position', [0.05 0.8 0.5 0.09]);

  h.boton_grafica = uicontrol ('style', 'pushbutton',...
			       'units', 'normalized',...
			       'string', 'Grafica de funciones',...
			       'callback', @menu_grafica,...
			       'position', [0.05 0.7 0.5 0.09]);

  h.boton_curvas = uicontrol ('style', 'pushbutton',...
			      'units', 'normalized',...
			      'string', 'Curvas de Bezier',...
			      'callback', @actualizar_plot,...
			      'position', [0.05 0.6 0.5 0.09]);

  % Si necesitan añadir nuevos botones copien un boton de arriba y reduzcan en
  % 0.1 el segundo elemento del vector posicion, en string poner una
  % descripcion de su menu y en callback el nombre de su funcion con un arroba
  % al inicio.

end
